### PR TITLE
#1246

### LINKED ISSUE #1246: NoSlowB lags back when it shouldn't
When a player has `grim.nosetback`, the player will still get lagged back when flagging NoSlowB.

Server version: git-PaperSpigot-445
Grim version: 27397f9
Plugins:
- grimac 2.3.48
- EssentialsX 2.20.1
- LuckPerms 5.4.108

### PR DESCRIPTION
**Pull request by ManInMyVan**
fixes #1246

### CODE REVIEW

**Comment by SamB440** [comment]
Probably better to just add an or for nosetback permission... I'm not sure if this change would break anything

**Comment by ManInMyVan** [comment]
> Probably better to just add an or for nosetback permission...

Can you explain what you mean by this?

**Comment by SamB440** [comment]
isExempt checks lastGoodPosition instead of requiredSetback so I am worried that breaks something

**Comment by AoElite** [comment]
@ManInMyVan Change it to a permission, it shouldn't be using isExempt().

**Pull request merged**
