### PR TITLE
Add BadPacketsV

### PR DESCRIPTION
**Pull request by z7087**
Deny action number in click window packets to prevent vanilla server send negative action number transaction
If this is able to false then maybe we should change our max transaction packet id

### CODE REVIEW

**Comment by AoElite** [comment]
@z7087 Does this fix a crash? It's a bit unclear.

**Comment by z7087** [comment]
no

**Comment by AoElite** [comment]
Have you tested this with the via plugins?

**Comment by z7087** [comment]
no but looked into mcp 1.8.8/1.12 and viaversion, should work

**Comment by z7087** [comment]
players can click inventory 32768 times to false this
maybe add a accepted check when grim send transactions?
or change all <=0 actionid to 1 in window-click packets

**Pull request closed without merging**
