### PR TITLE
Add BadPackets2

### PR DESCRIPTION
**Pull request by ManInMyVan**
detects some bad keypearls and some switchitem noslows (full patch in #1469)

### CODE REVIEW

**Comment by overkidding** [comment]
BadPackets2
Falses in 1.8 (testing in production) gettings spam flags

**Comment by xEcho1337** [comment]
This can be bypassed by delaying the C09 to the next tick, also an heuristic check would be much better

**Comment by ManInMyVan** [comment]
> This can be bypassed by delaying the C09 to the next tick

I'm aware, I said some

**Comment by ManInMyVan** [comment]
> BadPackets2
> Falses in 1.8 (testing in production) gettings spam flags

Replication steps?

**Comment by overkidding** [comment]
> > BadPackets2
> > Falses in 1.8 (testing in production) gettings spam flags
> 
> Replication steps?

Just Fast switch items and click the ground fast

**Comment by ManInMyVan** [comment]
> > > BadPackets2
> > > Falses in 1.8 (testing in production) gettings spam flags
> > 
> > Replication steps?
> 
> Just Fast switch items and click the ground fast

Could not replicate on vanilla or lunar 1.8.9, maybe send a video?

**Comment by ManInMyVan** [comment]
> > > BadPackets2
> > > Falses in 1.8 (testing in production) gettings spam flags
> > 
> > 
> > Replication steps?
> 
> Just Fast switch items and click the ground fast

I think I fixed it, are you able to reproduce on 28b2a56e87da877444227f6706442a54318f4657?

**Comment by overkidding** [comment]
> > > > BadPackets2
> > > > Falses in 1.8 (testing in production) gettings spam flags
> > > 
> > > 
> > > Replication steps?
> > 
> > 
> > Just Fast switch items and click the ground fast
> 
> I think I fixed it, are you able to reproduce on [28b2a56](https://github.com/GrimAnticheat/Grim/commit/28b2a56e87da877444227f6706442a54318f4657)?

still falses

**Comment by overkidding** [comment]
image

**Comment by overkidding** [comment]
> > > > BadPackets2
> > > > Falses in 1.8 (testing in production) gettings spam flags
> > > 
> > > 
> > > Replication steps?
> > 
> > 
> > Just Fast switch items and click the ground fast
> 
> I think I fixed it, are you able to reproduce on [28b2a56](https://github.com/GrimAnticheat/Grim/commit/28b2a56e87da877444227f6706442a54318f4657)?

I confirm that this has been fixed

**Comment by ManInMyVan** [comment]
#1678

**Pull request closed without merging**
