### PR TITLE
Code optimization

### PR DESCRIPTION
**Pull request by MachineBreaker**

### CODE REVIEW

**Comment by UserNugget** [comment]
I think you can also replace `new HashSet<>(other-set-with-VectorData)` (like in https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java#L364) with `other-set-with-VectorData.toArray(new VectorData[0])`

**Comment by MachineBreaker** [comment]
> I think you can also replace `new HashSet<>(other-set-with-VectorData)` (like in
> 
> https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java#L364
> 
> ) with `other-set-with-VectorData.toArray(new VectorData[0])`

done

**Comment by UserNugget** [comment]
> > I think you can also replace `new HashSet<>(other-set-with-VectorData)` (like in
> > https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java#L364
> > 
> > ) with `other-set-with-VectorData.toArray(new VectorData[0])`
> 
> done

Oh, i forgot to mention, that there is many others:
https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/player/GrimPlayer.java#L267
https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java#L364
https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngineLava.java#L13
https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngineWaterLegacy.java#L51
https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngineNormal.java#L37

**Comment by MachineBreaker** [comment]
> > > I think you can also replace `new HashSet<>(other-set-with-VectorData)` (like in
> > > https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java#L364
> > > 
> > > ) with `other-set-with-VectorData.toArray(new VectorData[0])`
> > 
> > 
> > done
> 
> Oh, i forgot to mention, that there is many others:
> 
> https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/player/GrimPlayer.java#L267
> 
> 
> https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngine.java#L364
> 
> 
> https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngineLava.java#L13
> 
> 
> https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngineWaterLegacy.java#L51
> 
> 
> https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/predictionengine/predictions/PredictionEngineNormal.java#L37

done

**Comment by UserNugget** [comment]
And i want to ask Define, is `VectorData::hashCode` and `VectorData::equals` should use previous VectorData and debugging parameters?
https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/utils/data/VectorData.java#L55-L61
https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/utils/data/VectorData.java#L63-L66

**Comment by MWHunter** [comment]
> And i want to ask Define, is `VectorData::hashCode` and `VectorData::equals` should use previous VectorData and debugging parameters?
> 
> https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/utils/data/VectorData.java#L55-L61
> 
> 
> https://github.com/GrimAnticheat/Grim/blob/b51c6521a9d1c48c16266355f2c138c07932a198/src/main/java/ac/grim/grimac/utils/data/VectorData.java#L63-L66

no.  Previous vectors are for debugging purposes and aren't used in any part of the engine other than grim logs.

**Comment by MachineBreaker** [comment]
I can't think how i can optimise more of the Grim code without big servers providing spark reports.

**Comment by EternalHuman** [comment]
CollisionData.class:

rawLookupArray[type.getMaterialType().ordinal()] = data;

This will break all the logic of the class. type.getMaterialType() is not something that needs to be added to the array

**Comment by EternalHuman** [comment]
All other optimizations look good. Especially "Verify cheap checks firstly".
@MachineBreaker you need to roll back CollisionData class.

**Comment by MachineBreaker** [comment]
Closing this to work in a fresh codebase

**Pull request closed without merging**
