### PR TITLE
Do not exempt fabric

### PR DESCRIPTION
**Pull request by AyazJenkins**
Fabric doesn't mean "trusted".

### CODE REVIEW

**Comment by vytskalt** [comment]
Feather should probably be removed as well

**Comment by SamB440** [comment]
Then lunar client should be removed as well, because there are still cheats you can inject into it.

To me, this ignored client list seems more like it's there to not spam operators with join alerts for common clients that people use.

I don't really see the benefit to removing any of them, it can all be faked by the client regardless.

**Comment by AoElite** [comment]
Just to clarify; this setting doesn't make clients exempt from the anticheat. It only disables the brand alert message that occurs when a player joins if their brand matches one of the regex. The main purpose is to catch unusual brands that don't follow popular or normal brands. I don't believe anyone here thinks that having any of those brands makes you trusted as its pretty well known brands are easily spoofable. If you wish to remove those brands in your configuration feel free to do so.

**Comment by AoElite** [comment]
If you wish to change the default behavior you can just edit your configuration. However many legitimate players use fabric & anyone flagging the anticheat should be considered suspicious period considering how easy it is to spoof brands.

**Pull request closed without merging**
