### PR TITLE
Improve FabricatedPlace

### PR DESCRIPTION
**Pull request by z7087**
Add check for NaN cursor to patch my ghostblock fly

### CODE REVIEW

**Comment by z7087** [comment]
Does Grim need to check if the sequence of the packet in higher versions of minecraft is less than 0? I think it might make ghost blocks as well, but I can't test it.

**Comment by AoElite** [comment]
@z7087 Maybe this should be its own check.

**Comment by z7087** [comment]
I think it's fine now

**Comment by AoElite** [comment]
10a99fd67bcf98417b200289161dafbb4d454f77

**Pull request closed without merging**
