### PR TITLE
Add AimRounded Check.

### PR DESCRIPTION
**Pull request by InetAddress**
From my testing this is a half decent check at detecting some weird scaffold rotations.
I did not test with any sort of lag I did bridge for a bit and not false flags but I am also terrible at bridging "I'm not some sort of godbridger from bridger.land" but I think it works pretty good.

may need further review.

### CODE REVIEW

**Comment by InetAddress** [comment]
Also didn't mention this but I am kind of at my learning curve for development so I would love some constructive feedback even if it is negative.

**Comment by jonesdevelopment** [comment]
Hello, I recommend checking for delta yaw/pitch values instead, as you will have to account for many different edge cases now. Additionally, Grim 2.0 isn't supposed to contain such checks, as that would make it extremely easy for cheat developers to bypass these checks if they're open source.

> With checking for the delta yaw/pitch values, you're gonna run into some other edge cases, but it's still a lot safer than using the absolute values.

Last but not least, I wanted to point out is a false positive with vehicles/riding entities:

https://github.com/user-attachments/assets/18148bf4-4752-44ce-89f4-1efb0215d6b9

**Comment by InetAddress** [comment]
I see, so what do you recommended rewriting the check like? If its even worth rewriting to be better and like you said its not worth having these types of checks in the anticheat.

**Comment by jonesdevelopment** [comment]
There are some older clients who are not going to account for this flaw, however, it's fixed in pretty much every modern client.

A good example of a rounding check can be found in my fork [here](<https://github.com/jonesdevelopment/Grim/tree/2.0/src/main/java/ac/grim/grimac/checks/impl/aim>). It's not perfect by any means, but it does work and I haven't found any false positives with it yet.

**Comment by InetAddress** [comment]
Oh ok, are you still waiting for you aim checks to be pulled then I would imagine?

**Comment by jonesdevelopment** [comment]
> Oh ok, are you still waiting for you aim checks to be pulled then I would imagine?

No, the changes on my fork is not meant to/designed to be merged into the main version of Grim.

**Comment by InetAddress** [comment]
Ok, Well thanks for the feedback I will definitely try to do better / more vigorous testing before making a PR.

**Pull request closed without merging**
