### PR TITLE
Added instant respawn check

### PR DESCRIPTION
**Pull request by NonSwag**
The check I've added makes it impossible for cheaters to instantly respawn even though the **doImmediateRespawn** game rule is turned off

### CODE REVIEW

**Comment by MachineBreaker** [comment]
Also, does this check runs on older versions? if not, i think you can just skip the gamerule check for older versions if you do an ServerVersion check

**Comment by MWHunter** [comment]
What if the server sends two respawns rapidly?  So the player clicks respawn on the first before getting the second death

**Comment by NonSwag** [comment]
That would never happen in unmodified gameplay.
Even when the packet gets manually send twice at once the client respawn cooldown will get reset and so the players server cooldown

**Comment by NonSwag** [comment]
I don't know if it works on older versions, the cheat is made for servers that support this game rule.

**Comment by MachineBreaker** [comment]
> I don't know if it works on older versions, the cheat is made for servers that support this game rule.

Older versions doesn't have this Game Rule, you could skip it since it would be false in that case and to prevent exceptions due to api changes.

Or if you want, check the server version firstly before any verification

**Comment by MWHunter** [comment]
>  Even when the packet gets manually send twice at once the client respawn cooldown will get reset and so the players server cooldown

Latency exists, you aren't accounting for this latency.

**Comment by caoli5288** [comment]
I believe that latency, lagging(from client or server), and others can lead to false. This is not a stable detection.

**Pull request closed without merging**
