### PR TITLE
Add camel support

### PR DESCRIPTION
**Pull request by c0dingnoobi**
Ok so basically, this pr aims to fix false positives for camels (sprinting on them and jumping) mentioned in #1059 and #1157

There are currently 2 issue which i couldn't yet solve:
- Detecting if camel refuses to move to set horizontalInput to 0
- Sprint Dashing somehow causes offsets (avoided with uncertainty offset reducing)
Intention for this PR is mostly to seek for help lol

### CODE REVIEW

**Comment by Huge-mistake** [comment]
Any progress? I want to ride a camel😍

**Comment by c0dingnoobi** [comment]
for now i have added an uncertainty of 0.1 blocks (which is high im aware of that) when sprint dashing (works fine without sprint) until someone might come up with a solution

**Comment by SamB440** [comment]
Perhaps the offset is caused by updating the movement speed in the wrong place. You are doing it on init, but in vanilla the movement speed of the vehicle is updated just before the entity travel method is called. So, it happens after stuff like jumping, which means the speed will be wrong vs vanilla because the camel is now dashing.

**Comment by CatTeaA** [comment]
Very much looking forward to being able to ride a camel

**Comment by BangXi** [comment]
wink wink❤

**Comment by Pman3** [comment]
Any updates? I still can't ride a camel properly. :(

**Comment by SamB440** [comment]
This PR does not handle camels correctly, I will fix the engine myself when I have time

**Pull request closed without merging**
