### PR TITLE
Fix #981

### LINKED ISSUE #981: Pressing W and S simultaneously in boat on ice falses Simulation
### Describe the false positive and how to replicate it

1. Join via 1.19.3 client.
2. Place a boat onto ice.
3. Ride it.
4. Press W and S at the same time.
5. Simulation falses and you get kicked out of the boat.

https://paste.grim.ac/tWJoj

### Grim version

050eb72

### Server version

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version

### Plugins

ViaVersion, ViaBackwards, GrimAC

(Via is not active here, client and server versions match)

#### Edit
Works **in water**, not on ice only.

### PR DESCRIPTION
**Pull request by UserNugget**
Boats can move forward and backward at same time, but packet can only show one state

### CODE REVIEW

**Comment by MWHunter** [comment]
Will double check against source code - this doesn't seem like something that would need brute force

**Comment by UserNugget** [comment]
According to source code 1.9+ clients allowing forward+backward combination, but at same time send 0 as forward movement if both forward and backward buttons being pressed.

I dont think this can be done without bruteforce.

**Comment by MachineBreaker** [comment]
> Will double check against source code - this doesn't seem like something that would need brute force

Any result?

**Comment by UserNugget** [comment]
Fixed a conflict and documented properly
Should look much better now

**Comment by Hwaanx** [comment]
any updates?

**Comment by SamB440** [comment]
I can confirm this and the fix is correct, this should be merged.

Probably fixes #927 as well?

**Pull request merged**
