### PR TITLE
French Translations

### PR DESCRIPTION
**Pull request by Mimexe**
Added fr.yml to resources/messages. ~~Only comments are not translated (doubt with the uploads messages)~~ Comments are now translated

### CODE REVIEW

**Comment by Mimexe** [comment]
Added fr.yml to others folders

**Comment by MaledictYtb** [comment]
I have already opened a pull request to add French translations. Can I use your translations to improve mine ?

**Comment by Mimexe** [comment]
I just viewed your pull request, and Yeah you can I you want

**Comment by c0dingnoobi** [comment]
@Mimexe @MaledictYtb can one of you close ur current pr, unnecessary to have two identical prs open

**Comment by MaledictYtb** [comment]
@Mimexe Can you close yours and see if mine is good for you ? In my opinion mine is better.

**Pull request closed without merging**
