### PR TITLE
fix 1.21 clients on pre-1.21 servers flagging with fix-1_21-placement-rotation enabled

### PR DESCRIPTION
**Pull request by ManInMyVan**

### CODE REVIEW

**Comment by Cyramek** [comment]
https://github.com/GrimAnticheat/Grim/pull/1754#issuecomment-2404942201

**Comment by Cyramek** [comment]
also I think you should check server version as this would allow bypasses on >=1.21 servers, like I did here: https://github.com/GrimAnticheat/Grim/pull/1754/commits/c8ff1109e1538eaa70529748fc9e8de3ce50e721

**Comment by SamB440** [comment]
I am against this.

**Comment by AoElite** [comment]
We can probably properly fix this once we switch to grim's packetevents fork which we can use to listen to packets before via.

**Pull request closed without merging**
