### PR TITLE
Implement NoSlowB

### LINKED ISSUE #602: Grim doesn't check food level on sprinting
**Describe the bug**
Grim doesn't check the food level if a player is sprinting.

**To Reproduce**
If you remove the check for the food level in the `LocalPlayer#aiStep` (mojang mappings) method, the player can sprint while having a food level less than 6.

**Server Version:**
1.18.2 (Client Version is 1.19)

**Grim Version (Git commit or the version in the jar's name)**
95bda9f7dcb29553f03a131e6f15032a950fe97f, 7 commits behind

**Relevant plugins**
none

### PR DESCRIPTION
**Pull request by c0dingnoobi**
Resolves #602 
Basically impossible to false

### CODE REVIEW

**Comment by MachineBreaker** [comment]
Has been tested with modified clients, vanilla and canFly status on ground, also flying (Not 1:1 MCP but does the job)

**Review by MachineBreaker — APPROVED** [review]

**Comment by MWHunter** [comment]
This flags once but doesn't stop illegitimate movement

**Comment by c0dingnoobi** [comment]
@MWHunter should work fine now

**Comment by MachineBreaker** [comment]
New changes tested and works properly, blocks illegitimate movement and is stable

**Pull request merged**
