### PR TITLE
Allow disabling max-ping-out-of-flying

### PR DESCRIPTION
**Pull request by Anthony01M**
image

### CODE REVIEW

**Comment by SamB440** [comment]
I don't understand, why would you need to disable this, it was mainly bedwars plugins that caused the "fly disabler" in the first place due to the player having their abilities set to fly. The comment makes it sound like having that setting enabled is the cause of a disabler.

**Comment by Anthony01M** [comment]
> I don't understand, why would you need to disable this, it was mainly bedwars plugins that caused the "fly disabler" in the first place due to the player having their abilities set to fly. The comment makes it sound like having that setting enabled is the cause of a disabler.

for me it's pretty clear that you should only disable it if you have a bedwars plugin and you're seeing fly disabler on your bedwars server, but maybe not for others, what do you suggest I change it to?

**Comment by SamB440** [comment]
> disable it if you have a bedwars plugin and you're seeing fly disabler on your bedwars server

But this setting is what prevents such a disabler?

**Comment by SamB440** [comment]
In the future use git add then `git commit --amend`, close editor, `git push --force` to avoid creating a ton of commits, my method will keep 1 commit with all the changes

**Pull request merged**
