### PR TITLE
Fix BadPacketsH and register ActionManager

### LINKED ISSUE #519: Noswing bypass
**Describe the bug**
Players can break/place blocks and attack entities without swinging their hand. Not sure how this could be used to gain an advantage, but it just looks weird. Up to you if this is worth patching. And yes I did test if it was server side.

**To reproduce**
Use bleachhack from https://bleachhack.org/ and enable No Swing. (And also make sure the Option ServerSide is enabled.)

**Server Version:**
Paper 1.17.1

**Grim Version (Git commit or the version in the jar's name)**
2.2.14

### PR DESCRIPTION
**Pull request by MachineBreaker**
ActionManager was not registered, causing checks like the BadPacketsH (No Swing) to not work.

Resolves #519

### CODE REVIEW

**Comment by caoli5288** [comment]
Got lots false on 1.8.8 servers(much player joins use high version). Not tested in other versions.

**Comment by MachineBreaker** [comment]
> Got lots false on 1.8.8 servers(much player joins use high version). Not tested in other versions.

Does this falses on what client version?

**Comment by MachineBreaker** [comment]
Try this new commit @caoli5288

**Comment by caoli5288** [comment]
> > Got lots false on 1.8.8 servers(much player joins use high version). Not tested in other versions.
> 
> Does this falses on what client version?

I tested same patch earlier this month and about 10% of the players false.

I'm not so sure they versions since grim's logs don't print the player's client version, but I'm guessing most of them are high versions.

**Comment by MachineBreaker** [comment]
> > > Got lots false on 1.8.8 servers(much player joins use high version). Not tested in other versions.
> > 
> > 
> > Does this falses on what client version?
> 
> I tested same patch earlier this month and about 10% of the players false.
> 
> I'm not so sure they versions since grim's logs don't print the player's client version, but I'm guessing most of them are high versions.

Did you tested the new commit?

**Comment by caoli5288** [comment]
> > > > Got lots false on 1.8.8 servers(much player joins use high version). Not tested in other versions.
> > > 
> > > 
> > > Does this falses on what client version?
> > 
> > 
> > I tested same patch earlier this month and about 10% of the players false.
> > I'm not so sure they versions since grim's logs don't print the player's client version, but I'm guessing most of them are high versions.
> 
> Did you tested the new commit?

I'm on vacation, maybe I'll test this patch next Monday.

**Comment by caoli5288** [comment]
@MachineBreaker Tested on 10k+ DAU network. looks no more falses

**Comment by MachineBreaker** [comment]
> @MachineBreaker Tested on 10k+ DAU network. looks no more falses

That's nice!

**Comment by MachineBreaker** [comment]
@MWHunter Wdyt about merging this?

**Comment by MWHunter** [comment]
The way you do this falses when over 20 CPS with a 1.8 client on a 1.9+ server due to viaversion doing ANIMATION ANIMATION ATTACK ATTACK

**Comment by c0dingnoobi** [comment]
suggestion: exempting when 1.8 client are on higher servers than 1.8 until vias [pr](https://github.com/ViaVersion/ViaRewind/pull/294) has been merged?

**Comment by MWHunter** [comment]
or keeping it like the current system that handles via's stupidity

**Comment by MachineBreaker** [comment]
> or keeping it like the current system that handles via's stupidity

The old behavior falses in 1.9+ due to the missing idle packet

**Comment by MWHunter** [comment]
that's a false negative not a false positive

**Comment by MWHunter** [comment]
That issue was never closed due to the "Players can break/place blocks" part of it

**Comment by MachineBreaker** [comment]
> that's a false negative not a false positive

So what do you recommend to do?

**Comment by MWHunter** [comment]
Check for block breaking and placing.  However, it could be difficult to know what's a block place due to it relying on inventory.  I personally don't believe block place NoSwing is worthwhile to check.  Block breaking could check for animations fine... I just don't see how it's an advantage.

I would just close the original issue as WONTFIX

**Comment by MachineBreaker** [comment]
> Check for block breaking and placing. However, it could be difficult to know what's a block place due to it relying on inventory. I personally don't believe block place NoSwing is worthwhile to check. Block breaking could check for animations fine... I just don't see how it's an advantage.
> 
> I would just close the original issue as WONTFIX

We could close it yeah, it's a pain in the ass to workaround ViaRewind

**Comment by scarfacered** [comment]
Could possibly merge this now? Fix was merged - https://github.com/ViaVersion/ViaRewind/pull/294

**Comment by c0dingnoobi** [comment]
> Could possibly merge this now? Fix was merged - [ViaVersion/ViaRewind#294](https://github.com/ViaVersion/ViaRewind/pull/294)

bump

**Pull request merged**
