### PR TITLE
Add detections for brand spoof

### PR DESCRIPTION
**Pull request by alec-jensen**
This adds a method to GrimPlayer to check if they are trying to spoof their brand. Detection is currently based on 2 things:
- is the brand vanilla, and do they have FastMath?
OR
- is the lunarclient brand incorrect

if someones brand is detected as spoofed, whenever we show the brand, it will say `(likely spoofed)` at the end
you can also enable alerts when it detects someone trying to spoof their brand

This depends on [this PR](https://github.com/GrimAnticheat/GrimAPI/pull/3). Once it gets accepted, I will update the GrimAPI requirements for this PR to be correct.

### CODE REVIEW

**Comment by MWHunter** [comment]
Optifine claims to be a vanilla client, this doesn't work

**Comment by alec-jensen** [comment]
> Optifine claims to be a vanilla client, this doesn't work

I tested myself, with standalone the brand is optifine, and forge, the brand is forge. Anyways, aoelite told me he wouldn't merge it

**Comment by VidTu** [comment]
> > Optifine claims to be a vanilla client, this doesn't work
> 
> I tested myself, with standalone the brand is optifine, and forge, the brand is forge. Anyways, aoelite told me he wouldn't merge it

test older versions of optifine, like 1.16.5

**Comment by Finoway** [comment]
When connecting to a Paper 1.8.8 server with ViaVersion, my client uses Fabric with the Fabric API mod (https://modrinth.com/mod/fabric-api/version/0.88.1+1.20.1).
 Fabric API sends a specific packet to the server, as indicated in the ViaVersion logs:
```
[21:34:59 WARN]: [ViaVersion] Ignoring incoming plugin channel register of 'fabric-screen-handler-api-v1:open_screen', as it is longer than 32 characters.
```

Additionally, when using Quilted Fabric API (https://modrinth.com/mod/qsl/version/7.2.1+0.88.0-1.20.1), which is only usable under Quilt, ViaVersion logs the following:
```
[21:53:04 WARN]: [ViaVersion] Ignoring incoming plugin channel register of 'quilt_registry_entry_attachments:sync', as it is longer than 32 characters
[21:53:04 WARN]: [ViaVersion] Ignoring incoming plugin channel register of 'qsl:registry_sync/registry_restore', as it is longer than 32 characters
[21:53:04 WARN]: [ViaVersion] Ignoring incoming plugin channel register of 'qsl:registry_sync/validate/fluid_states', as it is longer than 32 characters
[21:53:04 WARN]: [ViaVersion] Ignoring incoming plugin channel register of 'quilt:extended_entity_spawn_packet', as it is longer than 32 characters
[21:53:04 WARN]: [ViaVersion] Ignoring incoming plugin channel register of 'qsl:registry_sync/validate/block_states', as it is longer than 32 characters
```

To enhance the detection of spoofed brands, I suggest accepting "fabric" and "quilt" as valid brands for Fabric API, and only "quilt" for Quilted Fabric API.

**Comment by Finoway** [comment]
When connecting to a Paper 1.8.8 server with ViaVersion, my client uses the Owo lib mod ( tested version available here: https://modrinth.com/mod/owo-lib/version/0.11.1+1.20 ), which sends a specific packet, as indicated in the ViaVersion logs:
```
[22:10:21 WARN]: [ViaVersion] Ignoring incoming plugin channel register of 'owo:sync_screen_handler_properties', as it is longer than 32 characters.
```

To further improve detection of brand spoofing, we can treat any brand other than "fabric" or "quilt" as potentially spoofed when this mod is detected.

**Comment by SkyplayYT** [comment]
Lunar and Badlion has an API too. You could check that too.

**Comment by Finoway** [comment]
> Lunar and Badlion has an API too. You could check that too.

It seems to me that LabyMod does too, and labymod returns the brand "labymod" (tested with LabyMod 4 for 1.8.9, 1.12.2, 1.16.5, 1.17.1, 1.18.2, 1.19.2, 1.19.3, 1.19.4, 1.20.1 but not the LabyMod 4 version for 1.20.2-pre2) according to grim

**Comment by Finoway** [comment]
> > > Optifine claims to be a vanilla client, this doesn't work
> > 
> > 
> > I tested myself, with standalone the brand is optifine, and forge, the brand is forge. Anyways, aoelite told me he wouldn't merge it
> 
> test older versions of optifine, like 1.16.5

There is also to think that many launcher use optifine for example labymod there is an addons "OptiFine" knowing that labymod puts its brand "labymod" (I just tested under LabyMod 4.0.11 on minecraft 1.20.1)

**Comment by SkyplayYT** [comment]
> There is also to think that many launcher use optifine for example labymod there is an addons "OptiFine" knowing that labymod puts its brand "labymod" (I just tested under LabyMod 4.0.11 on minecraft 1.20.1)

You're right. It won't do you any good, since many hack clients use Optifine themselves too. I would rather check if they are trying to spoof a known client. With the API of LabyMod, Badlion, Lunar Client you can rather find out if the user spoofed his client.

**Comment by SkyplayYT** [comment]
Check if he is using Lunar client and send an API request. If he does not respond, he is spoofing his client.

**Pull request closed without merging**
