### PR TITLE
Add MultiActions Checks

### LINKED ISSUE #1195: Multitask/autoblock checks
### Feature description

Add a check for if a player uses an item and breaks a block/attacks an entity, because to my knowledge, it is not possible to attack entities or (in versions after 1.7.10) mine blocks while using items.

### PR DESCRIPTION
**Pull request by ManInMyVan**
checks for doing multiple things at the same time, also moves BadPacketsV into this check type/category

closes #1195

### CODE REVIEW

**Review by SamB440 — APPROVED** [review]

**Comment by Anthony01M** [comment]
LGTM

**Comment by overkidding** [comment]
MultiActionsE falses with CMClient and oldanimationsmod

**Comment by ManInMyVan** [comment]
> MultiActionsE falses with CMClient and oldanimationsmod

ask them to fix it then?

**Comment by AoElite** [comment]
@ManInMyVan I'm fine to merge since everything is experimental if you are done with this PR

**Comment by ManInMyVan** [comment]
> @ManInMyVan I'm fine to merge since everything is experimental if you are done with this PR

yeah I'm done

**Comment by Ayouuuu** [comment]
MultiActionC, MultiActionD false when swimming

**Comment by ManInMyVan** [comment]
> MultiActionC, MultiActionD false when swimming

should be an easy fix

**Review by SamB440 — APPROVED** [review]

**Pull request merged**
