### PR TITLE
Update PacketEntityAction.java

### PR DESCRIPTION
**Pull request by ghost**
Fixes elytra speed hack
https://discord.com/channels/811396969670901800/1132037476345716776/1142410390815383715
https://www.youtube.com/watch?v=vaAu-gRcaHc

### CODE REVIEW

**Comment by MWHunter** [comment]
This doesn't entirely fix it, the player doesn't take much friction when using an elytra, and jumping is allowed with an elytra for some god damn reason - which adds to the velocity.

Mojang is quite stupid and made start flying client sided and stop flying server sided.  This means due to latency this is perfectly vanilla.

Perhaps a config that sets back if you are moving horizontally greater than X blocks/tick, are using an elytra, and jump?

**Comment by MWHunter** [comment]
I'll just do it myself.  It's not possible with latency over 50 ms, and it's truly mojang's fault for implementing elytra in this terrible, terrible, way.

Can be configured to be fixed with https://github.com/GrimAnticheat/Grim/commit/b1bac5efb6e9121a7ed2a0ee0ee2201cdcbb49d3

**Comment by ghost** [comment]
This isn't an elytra speed hack its an intended vanilla feature. It's just running and jumping on the ground and spamming space bar.

**Comment by MWHunter** [comment]
This is a bug introduced with 1.14.  It's not an intended gameplay mechanic to be able to sprint jump with an elytra.  Mojang just never thinks of the consequences of making random stuff client sided.

**Pull request merged**
