### PR TITLE
Check for unknown client versions for players

### PR DESCRIPTION
**Pull request by Dg32z**
this will fix some plugins that cannot get player data when PlayerJoinEvent

### CODE REVIEW

**Comment by SamB440** [comment]
I have no idea what this does?

**Comment by Dg32z** [comment]
> I have no idea what this does?

I found during testing that the UNKNOWN client version can slow down player joining, which can cause some plugins to be unable to store player data properly.

**Comment by Dg32z** [comment]
> I have no idea what this does?

this can be seen on the plugins that connect to the database. If there is a delay in the database, it will cause those plugins to be unable to retrieve player data

**Comment by Dg32z** [comment]
PacketEvent issue

**Pull request closed without merging**
