### PR TITLE
Add Quilt client brand

### PR DESCRIPTION
**Pull request by vytskalt**
https://quiltmc.org/

### CODE REVIEW

**Comment by VidTu** [comment]
`forge` (1.13+) and `fml,forge` (pre-1.13) can be added in exempted mods too, but I don't understand printing brand on join if all mods are ignored. (or is this check for very very stupid hack client devs who put their client name in the brand?; personally i saw some hacks having `1.12.2`, `1.16.5`, `vanila` [with one L] as a brand, not sure why and how)

**Comment by MWHunter** [comment]
Why do we exempt fabric?

**Comment by VidTu** [comment]
I don't know why do we exempt fabric iirc there was pull request with that changes that was merged see `git blame`

**Comment by VidTu** [comment]
I just don't know what this notification should do (initial purpose) by default:
1. Show all modded (non-`vanilla`) clients. (my personal preference)
2. Exempt all known non-hacked clients (e.g. forge, fabric, quilt, lunar) to see stupidity of hacked client devs who accidentally changed client brand.

**Pull request closed without merging**
