### PR TITLE
Refactoring post-flying block-place check, improved RotationPlace

### PR DESCRIPTION
**Pull request by z7087**
fix RotationPlace false in 0.03 and bad wifi, and now RotationPlace checks cursor
tested it on 1.19.2 spigot with 1.8.9 1.12.2 1.20.1 client and 1.8.8 spigot with 1.7.10 1.12.2 client, but i dont know how much cursor threshold safe on 1.11- server

### CODE REVIEW

**Review by Nightsky000 — COMMENTED** [review]
add more comments please

**Comment by z7087** [comment]
#1185
RotationPlace falses for vanilla players sometimes by drop rotation in a flying packet, so i saved the rotation to update
and many of the clients I've used flag the FabricatedPlace check sometimes, so i tried writing this check on the cursor of the PlayerBlockPlacement packet to check them more strictly

**Comment by z7087** [comment]
then just check the cursor is or not vaild for the facing to deny player from place a block with north facing and 0.5,1,0.5 cursor

**Comment by z7087** [comment]
> then just check the cursor is or not vaild for the facing to deny player from place a block with north facing and 0.5,1,0.5 cursor

if the player is not inside the block and the block have no special hitbox, then he must can only click on a max cursor on a side, for example facing=up then the cursor y must be 1.0

**Comment by AoElite** [comment]
@z7087 Is this ready to be merged?

**Comment by z7087** [comment]
no this should make errors with #1285

**Comment by z7087** [comment]
ok now i think

**Comment by Souipi** [comment]
Reup ?

**Pull request closed without merging**
