### PR TITLE
1133 velocity patch

### PR DESCRIPTION
**Pull request by cattyngmd**

### CODE REVIEW

**Comment by ManInMyVan** [comment]
1. see [BadPacketsX](https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsX.java)
2. #1337 has nothing to do with velocity (did you mean #1133? if so, this isn't a full patch)
3. [Link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) so it get closed if/when this is merged

**Comment by cattyngmd** [comment]
yea it should close https://github.com/GrimAnticheat/Grim/issues/1133

**Comment by ManInMyVan** [comment]
> yea it should close #1133

rename the pull and link it, also this isn't a full patch

**Comment by cattyngmd** [comment]
> > yea it should close #1133
> 
> rename the pull and link it, also this isn't a full patch

well it will patch most of the cases
it will fail if theres a light block ig or smth like that

**Comment by ManInMyVan** [comment]
[rename](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message) the commit too

**Comment by ManInMyVan** [comment]
> well it will patch most of the cases it will fail if theres a light block ig or smth like that

this is a workaround and not an actual patch (which is why BadPacketsX didn't close it)

**Comment by ManInMyVan** [comment]
This does basically the same thing as BadPacketsX (flagging cancels the packet which is checked before handling)

**Comment by cattyngmd** [comment]
> This does basically the same thing as BadPacketsX (flagging cancels the packet which is checked before handling)

i guess its not, cuz badpacketsx doesnt check for air when u send finish destroy block

**Comment by SamB440** [comment]
The change makes sense nonetheless

**Comment by ghost** [comment]
1444 👁️ 👁️

**Pull request merged**
