### PR TITLE
idk

### PR DESCRIPTION
**Pull request by zyklone4096**

### CODE REVIEW

**Comment by MWHunter** [comment]
what does this check exactly?

**Comment by zyklone4096** [comment]
> what does this check exactly?

flight, but originally made for 1.12

**Comment by c0dingnoobi** [comment]
> flight, but originally made for 1.12

did you find a fly bypass or whats the reason behind implementing this check

**Comment by zyklone4096** [comment]
> > flight, but originally made for 1.12
> 
> did you find a fly bypass or whats the reason behind implementing this check

currently no bypass found, i decompile analysed some hacks to make this

**Comment by zyklone4096** [comment]
???

**Pull request closed without merging**
