### PR TITLE
false

### PR DESCRIPTION
**Pull request by TheTawnyYT**
https://paste.grim.ac/M2T3O

W tapping a lot on 1.8 Is the cause of it
no hacks
idk

### CODE REVIEW

**Comment by rafalohaki** [comment]
when v3?

**Comment by TheTawnyYT** [comment]
> when v3?

Never ig

**Comment by vytskalt** [comment]
define isnt even in the discord anymore

**Comment by TheTawnyYT** [comment]
Ik 😕

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
