### PR TITLE
Add BadPackets4

### LINKED ISSUE #1195: Multitask/autoblock checks
### Feature description

Add a check for if a player uses an item and breaks a block/attacks an entity, because to my knowledge, it is not possible to attack entities or (in versions after 1.7.10) mine blocks while using items.

### PR DESCRIPTION
**Pull request by ManInMyVan**
like BadPacketsV for blocks, closes #1195

### CODE REVIEW

**Comment by Anthony01M** [comment]
Safe to say you can move BadPacketsV and BadPackets4 to autoblock folder:
- BadPacketsV -> AutoBlockC
- BadPackets4 -> AutoBlockD

**Comment by ManInMyVan** [comment]
> Safe to say you can move BadPacketsV and BadPackets4 to autoblock folder:
> - BadPacketsV -> AutoBlockC
> - BadPackets4 -> AutoBlockD

This isn't an autoblock check, it's a multitask/multiactions check (it only applies to breaking blocks)

**Comment by Symmettry** [comment]
badpackets 1, 2, 3, 4 should be AA, AB, AC, AD

**Comment by ManInMyVan** [comment]
#1597

**Pull request closed without merging**
