### PR TITLE
Update Gradle and other dependencies

### PR DESCRIPTION
**Pull request by Obydux**
Tested on Purpur 1.20.4 and PandaSpigot 1.8.8, everything seems to work just fine. Also fixes the RBG issue

### CODE REVIEW

**Comment by EclipsesDev** [comment]
Grim devs must be very "busy" 🤦

**Comment by Symmettry** [comment]
Doesn't grim use protocollib not packetevents or am I missing something (e.g. does latest packetevents use protocollib?)

**Comment by EclipsesDev** [comment]
Grim does use packet event

**Comment by ManInMyVan** [comment]
> Doesn't grim use protocollib not packetevents or am I missing something (e.g. does latest packetevents use protocollib?)

Grim uses packetevents

**Pull request closed without merging**
